# Generated by Django 3.2.25 on 2024-10-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='blog_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
